### ISSUE TITLE
Selecting second slot on Echelon 2

### ISSUE THREAD

**Issue by fnzr** [dice4321/Gunkolle#54]
Hi,
I'm making a modification on the script to allow dual DPS corpse dragging (until my gold ammo decides to drop).
I already managed to replace 2 exhausted DPSers for for loaded DPSers on Echelon 1, but now I need to select the second slot of Echelon 2 to add the second exhausted DPS.
Currently, you do it at line 533 of Gunkolle.ahk, with `ClickS(Role1x,Role1y)`. I did some digging and `Role1x`  is `Role1x := FX - 111` . `FX` ends up being dependent of `PixelSearch` result, and I can't figure how to get the second slot position from that.
Any advice?

**Comment by f-matos** [comment]
Oh I got it, `Role2x := Role1x + 180` works, got the idea from `TdollRetirementSlot1x+180*rti` on Gunkolle.ahk.
Nice work on the script man, I think I'll try to write one for 5-2E or 5-4E since apparently I'm too much of a scrub to run 0-2 even with 2 DPSers.
Getting a bit out of the scope of the issue, but how do you create the pictures for the nodes? The tiny, identifiers ones. `pics/4-3eEnemy1.png` for example.

**Comment by dice4321** [comment]
oh nice, you got it to work even without my assistance 👍, sorry my code isnt the best well commented, I need to work on that, hope it didnt give you too much trouble! Looking forwards to that 5-2E!

**Comment by fnzr** [comment]
Even without comments the code is very readable, I was impressed with how easily I could understand it. Anyway, this issue is done.
