### ISSUE TITLE
MG weapon type

### ISSUE THREAD

**Issue by l2aYza** [dice4321/Gunkolle#67]
I'd like to farm equip fodder on 5-2N. How can I add MG for a new weapon type?

**Comment by dice4321** [comment]
First you need to add the assets, since I dont have a filter for MachineGun's you would need to add them yourself, and you would need to name this filter FilterMachineGun so that the script is able to parse the asset correctly. When you want to select MG for the switch, you would always need two available as well as changing the config filter to `WeaponType=MachineGun`. Then you would add the MG assets, one for the formation and one for the profile. Then change the 5Star/4Star array in the `Initialize()` function to include the dolls you want to switch. Then you would create the map itself because Gunkolle does not support 5-2N.
